version: "3"

services:
  srtm-service:
    build: .
    container_name: ${SRTM}
    hostname: ${SRTM}
    environment: 
      PORT: ${SRTM_PORT}
    networks:
      - dtm
    restart: unless-stopped
    volumes:
      - ./data:/srtm-service/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.srtm-service.rule=Host(`${SRTM_SERVER}`)"
      - "traefik.http.routers.srtm-service.entrypoints=websecure"
      - "traefik.http.routers.srtm-service.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.srtm-service.loadbalancer.server.port=${SRTM_PORT}"
    logging:
      driver: "gelf"
      options:
        gelf-address: ${GRAYLOG_SERVER}
        tag: ${SRTM}
networks:
  dtm:
    external: true
