version: "3"

services:
  srtm-service:
    build: .
    container_name: ${SRTM}
    hostname: ${SRTM}
    networks:
      - dtm
    restart: unless-stopped
    environment: 
      PORT: ${SRTM_PORT}
    ports:
      - "${SRTM_PORT}:${SRTM_PORT}"
    labels:
      - traefik.enable=false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
networks:
  dtm:
    external: true
